version: "3"
services:

  zookeeper:
    image: zookeeper:3.4.9

  kafka:
    depends_on:
      - zookeeper
    image: doubletrade/kafka:0.11.0.2
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9999:9999"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_INTER_BROKER_PROTOCOL_VERSION=0.11.0
      - KAFKA_LOG_MESSAGE_FORMAT_VERSION=0.11.0
      - KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS=10000
      - JMX_PORT=9999
